name: My First CI

on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files
        run: ls

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: List files
        run: ls -la